version: "3.9"

services:
  backend:
    container_name: fastapi_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    restart: unless-stopped